#!/bin/bash

#  builddeps-cbfstool script: builds cbfstool (this script is for libreboot_bin)
#
#	Copyright (C) 2014 Francis Rowe
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# DO NOT RUN THIS IN libreboot_src OR libreboot_meta
# THIS IS FOR libreboot_bin

cd cbfstool_standalone
make clean
make
rm -rf ../cbfstool
rm -rf ../rmodtool
mv cbfstool ..
mv rmodtool ..
make clean
cd ..
