#!/bin/bash

#  builddeps-coreboot: builds the dependencies that coreboot needs before building a ROM image
#
#	Copyright (C) 2014 Francis Rowe <info@gluglug.org.uk>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# This script is used by the main "builddeps" script in libreboot src/meta archives.
# The reason it is seperated here is so that coreboot can be built separately aswell.

set -u -e -v

# Build utilities needed in coreboot directory
# --------------------------------------------------------------------

cd coreboot

# -----------------------------------------
# Build the utilities required by libreboot
# -----------------------------------------

# cbfstool
cd util/cbfstool/
make
# nvramtool
cd ../nvramtool/
make
# cbmem
cd ../cbmem/
make

# done. go back to coreboot dir
cd ../../

# -------------------------------------
# build reference crossGCC for coreboot
# -------------------------------------
make crossgcc-i386

# done. go back to main libreboot_src directory
cd ../

# ------------------- DONE ----------------------
