#!/bin/bash

#  builddeps-flashrom: builds flashrom source code
#
#	Copyright (C) 2014 Francis Rowe <info@gluglug.org.uk>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# To build flashrom, you will need the dependencies (see docs).

set -u -e -v

# Build "flashrom" (utility for flashing/dumping ROM's)
# --------------------------------------------------------------------

cd flashrom/

# build regular flashrom (redundant flash chip definitions removed)
make clean
if (( $# != 1 )); then
	# build it dynamically linked
	make
else
	# build it statically linked
	make SHARED=0 CC='gcc -static'
fi

mv flashrom flashrom_normal

# build patched binaries for MX25L1605D and SST25VF016B flash chips
# - these patches are needed for initial installation on an X60 or T60
# - these patches are for people who have lenovo bios running
for patchname in "lenovobios_macronix" "lenovobios_sst"
do
	# first remove the existing build
	make clean
	rm -f flashrom_"$patchname"
	
	# backup the unpatched flashchips.c (it will be patched)
	cp flashchips.c flashchips.c_
	# patch flashchips.c
	patch flashchips.c < ../resources/flashrom/patch/"$patchname".diff
	
	if (( $# != 1 )); then
		# build it dynamically linked
		make
	else
		# build it statically linked
		make SHARED=0 CC='gcc -static'
	fi
	
	# Rename the binary based on the patch name
	mv flashrom flashrom_"$patchname"
	
	# restore unpatched flashchips.c
	rm -f flashchips.c
	mv flashchips.c_ flashchips.c
done

mv flashrom_normal flashrom

cd ../

# ------------------- DONE ----------------------

