#!/bin/bash

#  builddeps-memtest86 script: builds memtest86+ source code
#
#	Copyright (C) 2014 Francis Rowe <info@gluglug.org.uk>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

set -u -e -v

# This script is used by the main "builddeps" script in libreboot src/meta archives.
# The reason it is seperated here is so that MemTest86+ can be built separately aswell.

# To use this script, you will need the dependencies in "builddeb".
# Run it, or adapt it if you do not use an "apt-get" distro.

# This is also used by the "getmt86" script.

# Build MemTest86+ payload (for GRUB)
# --------------------------------------------------------------------

cd "memtest86+-5.01"

# clean it first
make clean

# build memtest86+
make

# done. go back to main directory
cd ../

# ------------------- DONE ----------------------
