#!/bin/bash

#  builddeps-flashrom: builds flashrom source code
#
#	Copyright (C) 2014 Francis Rowe <info@gluglug.org.uk>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# To build flashrom, you will need the dependencies (se docs).

set -u -e -v

# Build "flashrom" (utility for flashing/dumping ROM's)
# --------------------------------------------------------------------

cd flashrom/

# clean it first
make clean

# default flashchips.c
mv flashchips.c flashchips.c_

# build patched binary for libreboot X60/T60 (MX25L1605D chip)
# - this patch removes redundant definitions from flashchips.c
# - this patch removes the need to use the -c parameter in flashrom
# build patched binaries for MX25L1605D and SST25VF016B flash chips
# - these patches are needed for initial installation on an X60 or T60
# - these patches are for people who have lenovo bios running
for patchname in "_normal" "_lenovobios_macronix" "_lenovobios_sst"
do
	rm -f flashchips.c"$patchname"
	cp ../resources/flashrom/patch/flashchips.c"$patchname" flashchips.c
	rm -f flashrom"$patchname"
	if (( $# != 1 )); then
		# build it dynamically linked
		make
	else
		# build it statically linked
		make SHARED=0 CC='gcc -static'
	fi
	mv flashrom flashrom"$patchname"
	rm -f flashchips.c
done
mv flashrom_normal flashrom

# default flashchips.c
mv flashchips.c_ flashchips.c

cd ../

# ------------------- DONE ----------------------

