#!/bin/bash

#  builddeps-grub: builds GRUB source code
#
#	Copyright (C) 2014 Francis Rowe
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# This script is used by the main "builddeps" script in libreboot src/meta archives.
# The reason it is seperated here is so that grub can be built separately aswell.

# To use this script, you will need the dependencies in "builddeb".
# Run it, or adapt it if you do not use an "apt-get" distro.

# This is also used by the "getgrub" script.

# Build utilies needed for building GRUB payloads
# ---------------------------------------------------------------------

cd grub

# clean it first
make clean

# build grub
./autogen.sh
./configure --with-platform=coreboot
make

# done. go back to main directory
cd ../

# ------------------- DONE ----------------------
