#!/bin/bash

#  builddeps-bucts: builds bucts source code
#
#	Copyright (C) 2014 Francis Rowe <info@gluglug.org.uk>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# This script is used by the main "builddeps" script in libreboot src/meta archives.
# The reason it is seperated here is so that bucts can be built separately aswell.

set -u -e -v

# Build BUC.TS utility (needed for flashing ROM's on X60/T60 while Lenovo BIOS is running)
# --------------------------------------------------------------------

cd bucts

# clean it first
make clean

# build bucts
if (( $# != 1 )); then
	# build it dynamically linked
	make
else
	patch Makefile < ../resources/bucts/patch/staticlink.diff
	# build it statically linked
	make
	patch Makefile -R < ../resources/bucts/patch/staticlink.diff
fi

# done. go back to main directory
cd ../

# ------------------- DONE ----------------------
