#!/bin/bash

#  builddeps script: builds the dependencies needed for 'build' to compile the ROM images
#
#	Copyright (C) 2014 Francis Rowe <info@gluglug.org.uk>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# This builds all of the dependencies that the "build" script relies on.

# MAKE SURE THAT YOU RAN "./builddeb" BEFORE RUNNING THIS!
# IF YOUR DISTRO DOESN'T USE "apt-get", ADAPT WHAT YOU SEE IN "builddeb"
# AND INSTALL THE BUILD DEPENDENCIES NEEDED TO RUN THIS BUILD SCRIPT!

# NOTE: If you downloaded the "meta" archive and ran "getall", then
# you do not need to run this at all. getall does all of the below:

set -u -e -v

# Build utilities needed in coreboot directory
# --------------------------------------------------------------------

./builddeps-coreboot

# Build utilies needed for building GRUB payloads
# ---------------------------------------------------------------------

./builddeps-grub

# Build MemTest86+ payload (for GRUB)
# --------------------------------------------------------------------

./builddeps-memtest86

# Build BUC.TS utility (needed for flashing ROM's on X60/T60/X60T while Lenovo BIOS is running)
# --------------------------------------------------------------------

./builddeps-bucts

# Build "flashrom" (utility for flashing/dumping ROM's)
# --------------------------------------------------------------------

./builddeps-flashrom

# Build SeaBIOS (legacy X86 BIOS payload for coreboot)
# --------------------------------------------------------------------

./builddeps-seabios

# Build GRUB Invaders
# --------------------------------------------------------------------

./builddeps-grubinvaders

# Build i945-pwm
# --------------------------------------------------------------------

./builddeps-i945pwm

# ------------------- DONE ----------------------


