#!/bin/bash

#  builddeps-ich9deblob: builds ich9deblob source code
#
#	Copyright (C) 2014 Francis Rowe <info@gluglug.org.uk>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# This script is used by the main "builddeps" script in libreboot src/meta archives.
# The reason it is seperated here is so that ich9deblob can be built separately aswell.

set -u -e -v

# Build ich9deblob utility
# --------------------------------------------------------------------

cd resources/utilities/ich9deblob

# clean it first
make clean

# build ich9deblob
make

# done. go back to main directory
cd ../../../

# ------------------- DONE ----------------------
