#!/bin/bash

#  download script: Download the programmes used in libreboot, that
#                   aren't distributed in the git repository.
#
#	Copyright (C) 2014, 2015 Francis Rowe <info@gluglug.org.uk>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

[ "x${DEBUG+set}" = 'xset' ] && set -v
set -u -e

download=./resources/scripts/helpers/download
programme="unknown"

usage="./download programme"
availableprogrammes="$(ls $download/)"

# User specified no or too few/many parameters
if (( $# != 1 )); then
	printf "$usage\n\n"
	printf "possible values for 'programme':\neverything:\n$availableprogrammes\n\n"
	printf "Example (download everything): ./download everything\n"
	printf "Example (download coreboot): ./download coreboot\n\n"
	exit 1
fi
programme=$1

if [ "$programme" = "everything" ]; then
	for programme in $availableprogrammes; do
		$download/$programme
	done
elif [ -f "$download/$programme" ]; then
	$download/$programme
else
	printf "Invalid programme. Available programmes are:\neverything\n$availableprogrammes\n"
	exit 1
fi

# ------------------- DONE ----------------------
