#!/bin/bash

#  download script: Download the programmes used in libreboot, that
#                   aren't distributed in the git repository.
#
#	Copyright (C) 2014, 2015 Francis Rowe <info@gluglug.org.uk>
#	Copyright (C) 2015 Klemens Nanni <contact@autoboot.org>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

[ "x${DEBUG+set}" = 'xset' ] && set -v
set -u -e

download="resources/scripts/helpers/download"
programmes="$(ls ${download}/)"
noconfirm="0"

help () {
	printf "%s\n\n" "./download programme(s) # programmes are space separated, if specifing multiple programmes"
	printf "possible values for 'programmes':\nall:\n%s\n\n" "${programmes}"
	printf "Example (download everything): ./download all\n"
	printf "Example (download flashrom): ./download flashrom\n"
	printf "Example (download coreboot): ./download coreboot\n"
	printf "Example (download coreboot and flashrom): ./download coreboot flashrom\n"
	printf "Example (lists all available downloadable components): ./download list\n"
}

if [ $# -lt 1 ]; then
	printf "ERROR: download script: no argmunt given.\n"
	help
	exit 1
fi

if [ "${1}" = "--noconfirm" ] || [ "${1}" = "-y" ]; then
	noconfirm="1"
	shift 1
fi

case "${1}" in
	all)
		;;
	list)
		printf "possible values for 'programmes':\nall\n%s\n\n" "${programmes}"
		exit 
		;;
	help)
		help
		exit 
		;;
	*)
		for programme in "${@}"; do
			printf "%s" "${programmes}\n" | grep -wq "${programme}" || (printf "ERROR: Invalid programme '%s'. See ./download help.\n" "${programme}"; exit 1)
		done
		programmes="${*}"
		;;
esac

for programme in ${programmes}; do

	if [ "${noconfirm}" = "0" ]; then
		printf "Use \"./download --noconfirm\" or \"./download -y\" if you want to be rid of these confirmation dialogues.\n\n"
		if [ -d "${programme}/" ]; then
			printf "A %s/ directory already exists, delete it? [yN]: " "${programme}"
			read -r answer
			if [ "${answer}" = "y" ]; then
				rm -Rf "${programme:?}" && printf "Old %s directory deleted.\n\n" "${programme}"
			else
				printf "%s directory not deleted, and therefore not replaced.\n" "${programme}"
				continue
			fi
		fi
	fi

	"${download}/${programme}"
done
