#!/bin/bash

#  getbucts script: downloads bucts and patches it
#
#	Copyright (C) 2014 Francis Rowe
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# Get bucts and checkout last revision used

# Remove the old version that may exist
# -----------------------------------------------------------

echo "DOWNLOADING BUCTS"

rm -rf bucts

# Get bucts
# -----------------------------------------------------------

# download it using git
git clone git://git.stuge.se/bucts.git

# modifications are required
cd bucts

# Reset to the last commit that was tested
# -----------------------------------------------------------

git reset --hard dc27919d7a66a6e8685ce07c71aefa4f03ef7c07

# no patches required

# We don't need .git* (please submit all upstreamable changes directly to bucts upstream)
# removing them, to reduce the size of the archive
# rm -rf .git
# rm -rf .gitignore
# it was found to cause issues when deleting:
# GIT_DISCOVERY_ACROSS_FILESYSTEM not set

# we're done
cd ../

echo "BUCTS DOWNLOAD COMPLETE"

# ------------------- DONE ----------------------
