#!/bin/bash

#  getflashrom script: downloads flashrom and patches it
#
#	Copyright (C) 2014 Francis Rowe <info@gluglug.org.uk>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

set -u -e -v

# Get flashrom at the last previously tested revision

# Remove the old version that may still exist:
# ---------------------------------------------------------------------

echo "DOWNLOADING FLASHROM"

rm -rf flashrom

# Get flashrom
# ---------------------------------------------------------------------

# download it using subversion
svn co -r 1858 svn://flashrom.org/flashrom/trunk flashrom

# apply patches
cd flashrom/
# Add whitelist for X200:
patch board_enable.c < ../resources/flashrom/patch/x200whitelist.diff
cd ../

echo "FINISHED DOWNLOADING FLASHROM"

# ------------------- DONE ----------------------
