#!/bin/bash

#  getgrub script: Downloads GRUB and patches it.
#
#	Copyright (C) 2014 Francis Rowe <info@gluglug.org.uk>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

set -u -e -v

# Get GRUB, revert to commit last used and apply patches.

# Remove the old version that may still exist
# -------------------------------------------------------------------------------

echo "DOWNLOADING GRUB"

rm -rf grub

# Get latest GRUB
# -------------------------------------------------------------------------------

# download it using git
git clone git://git.savannah.gnu.org/grub.git

# modifications are required
cd grub

# Reset to the last commit that was tested
# --------------------------------------------------------------------------------

git reset --hard bac5d1a64ab4191058a8fd4c05f6b3b339e249e7

# Apply patches
# --------------------------------------------------------------------------------

# See resources/grub/patch/gitdiff 
# Replace "GNU GRUB version" in GRUB screen with "FREE AS IN FREEDOM"

# copy it from resources
git apply ../resources/grub/patch/gitdiff

cd ../
echo "FINISHED DOWNLOADING GRUB"

# ------------------- DONE ----------------------


