#!/bin/bash

#  getmt86: Downloads MemTest86+ and patches it
#
#	Copyright (C) 2014 Francis Rowe <info@gluglug.org.uk>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

set -u -e -v

# Get the last version of MemTest86+ used, apply patches, build it.

# You need the dependencies from ./builddeb to use this script.

# Remove the old version that may exist
# ----------------------------------------------------------------------------------

echo "DOWNLOADING GRUB INVADERS"

rm -rf grubinvaders

# Get latest memtest86+:
# ----------------------------------------------------------------------------------

# download it using wget
wget http://www.erikyyy.de/invaders/invaders-1.0.0.tar.gz

# extract it
tar -xf "invaders-1.0.0.tar.gz"

# delete the tar file (no longer needed)
rm -rf "invaders-1.0.0.tar.gz"

# rename directory (for consistency with script names)
mv invaders grubinvaders

# there are modifications required
cd grubinvaders

# Apply necessary patches
# ---------------------------------------------------------------------------------

# Apply patch mentioned on http://www.coreboot.org/GRUB_invaders
cp ../resources/grubinvaders/patch/diff.patch .
cp ../resources/grubinvaders/patch/compile.sh.patch .
patch < diff.patch
patch compile.sh < compile.sh.patch

# delete the copy of the patch (no longer needed)
rm -rf diff.patch
rm -rf compile.sh.patch

# we're done
cd ../

echo "FINISHED DOWNLOADING GRUB INVADERS"

# ------------------- DONE ----------------------


