#!/bin/bash

#  getmt86: Downloads MemTest86+ and patches it
#
#	Copyright (C) 2014 Francis Rowe <info@gluglug.org.uk>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# Get the last version of MemTest86+ used, apply patches, build it.

# You need the dependencies from ./builddeb to use this script.

# Remove the old version that may exist
# ----------------------------------------------------------------------------------

echo "DOWNLOADING MEMTEST86+"

rm -rf "memtest86+-5.01"

# Get latest memtest86+:
# ----------------------------------------------------------------------------------

# download it using wget
wget http://www.memtest.org/download/5.01/memtest86+-5.01.tar.gz

# extract it
tar -xf "memtest86+-5.01.tar.gz"

# delete the tar file (no longer needed)
rm -rf "memtest86+-5.01.tar.gz"

# there are modifications required
cd "memtest86+-5.01"

# Apply necessary patches
# ---------------------------------------------------------------------------------

# Remove the line in the Makefile (comment line 24) that makes memtest86+ connect to an scp server during build
# Set the following in config.h (to enable use of memtest86+ on serial port):

#	#define SERIAL_TTY 0
#	#define SERIAL_BAUD_RATE 115200

#	/* BEEP_MODE - Beep on error. Default off, Change to 1 to enable */
#	#define BEEP_MODE 1

# place the right config
rm -rf config.h
cp ../resources/memtest86/patch/config.h .

# place the right Makefile
rm -rf Makefile
cp ../resources/memtest86/patch/Makefile .

# (diff them with defaults to see what changed)

# we're done
cd ../

echo "FINISHED DOWNLOADING MEMTEST86+"

# ------------------- DONE ----------------------


