#!/bin/bash

#  getmt86: Downloads MemTest86+ and patches it
#
#	Copyright (C) 2014 Francis Rowe <info@gluglug.org.uk>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

set -u -e -v

# Get the last version of MemTest86+ used, apply patches, build it.

# Remove the old version that may exist
# ----------------------------------------------------------------------------------

echo "DOWNLOADING MEMTEST86+"

rm -rf "memtest86+-5.01"

# Get latest memtest86+:
# ----------------------------------------------------------------------------------

# download it using wget
wget http://www.memtest.org/download/5.01/memtest86+-5.01.tar.gz

# extract it
tar -xf "memtest86+-5.01.tar.gz"

# delete the tar file (no longer needed)
rm -f "memtest86+-5.01.tar.gz"

# there are modifications required
cd "memtest86+-5.01"/

# Apply necessary patches
# ---------------------------------------------------------------------------------

# place the right config
rm -f config.h
cp ../resources/memtest86/patch/config.h .

# place the right Makefile
rm -f Makefile
cp ../resources/memtest86/patch/Makefile .

# (diff them with defaults to see what changed)

# we're done
cd ../

echo "FINISHED DOWNLOADING MEMTEST86+"

# ------------------- DONE ----------------------


