#!/bin/bash

#  lenovobios_secondflash: flashes libreboot during 2nd boot, after 1st initial overwrite of the lenovo bios on X60/T60
#
#	Copyright (C) 2014 Francis Rowe <info@gluglug.org.uk>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

## Don't add here. errors are expected.
# set -u -e -v
set -v

# USE ROOT OR SUDO WHEN EXECUTING THIS

# for T60 or X60 owners with Lenovo BIOS
# does the 1st part of the flash before shut down

if (( $# != 1 )); then
	echo "Usage: ./lenovobios_firstflash yourrom.rom"
	echo "usage: ./lenovobios_firstflash path/to/yourrom.rom"
	echo "You need to specify exactly 1 file"
	exit
fi
if [ ! -f $1 ]; then
	echo "File not found!"
	exit
fi

# Flash it a 2nd time, to write upper 64K block
./flashrom/flashrom -p internal -w $1

# Advised. Reset back to 0.
{ # try
	./bucts/bucts 0
} || { # catch
	echo "WARNING: bucts not found, but if the image was flashed then it's probably safe."
	echo "A dd'd image (like libreboot's images) flashed with bucts=1 is ok. If the image is not dd'd and bucts=1,"
	echo "then you should run ./bucts 0 now, or remove the yellow cmos/nvram battery for a minute."
}
