#!/bin/bash

#  lenovobios_firstflash: flashes libreboot on an X60/T60 while Lenovo BIOS is running
#
#	Copyright (C) 2014 Francis Rowe <info@gluglug.org.uk>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

## Don't add here. errors are expected.
# set -u -e -v
set -v

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi
if (( $# != 1 )); then
	echo "Usage: ./lenovobios_firstflash yourrom.rom"
	echo "usage: ./lenovobios_firstflash path/to/yourrom.rom"
	echo "You need to specify exactly 1 file"
	exit 1
fi
if [ ! -f $1 ]; then
	echo "File not found!"
	exit 1
fi

bucts="unknown"
flashromsst="unknown"
flashrommacronix="unknown"
if [ -f "DEBLOB" ]; then
	bucts="./bucts/bucts"
	flashromsst="./flashrom/flashrom_lenovobios_sst"
	flashrommacronix="./flashrom/flashrom_lenovobios_macronix"
elif [ $(uname -i) = "i686" ] || [ $(uname -m) = "i686" ]; then
	bucts="./bucts/i686/bucts"
	flashromsst="./flashrom/i686/flashrom_lenovobios_sst"
	flashrommacronix="./flashrom/i686/flashrom_lenovobios_macronix"
elif [ $(uname -i) = "x86_64" ] || [ $(uname -m) = "x86_64" ]; then
	bucts="./bucts/x86_64/bucts"
	flashromsst="./flashrom/x86_64/flashrom_lenovobios_sst"
	flashrommacronix="./flashrom/x86_64/flashrom_lenovobios_macronix"
else
	echo "This script must be run on an i686 or x86_64 host. x86_64 is recommended."
	exit 1
fi

# Set bucts
# this means we are working in src
if [ ! -f "$bucts" ]; then
	echo "BUCTS failed. Make sure BUC.TS is 1, or else you will brick your machine. ABORTING so as to protect against bricking the machine."
	exit 1
fi

$(echo $bucts) 1

$(echo $flashromsst) -p internal -w $1
$(echo $flashrommacronix) -p internal -w $1


