#!/bin/bash

#  lenovobios_secondflash: flashes libreboot during 2nd boot, after 1st initial overwrite of the lenovo bios on X60/T60
#
#	Copyright (C) 2014 Francis Rowe <info@gluglug.org.uk>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

## Don't add here. errors are expected.
# set -u -e -v
set -v

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi
if (( $# != 1 )); then
	echo "Usage: ./lenovobios_secondflash yourrom.rom"
	echo "usage: ./lenovobios_secondflash path/to/yourrom.rom"
	echo "You need to specify exactly 1 file"
	exit 1
fi
if [ ! -f $1 ]; then
	echo "File not found!"
	exit 1
fi

# boardmismatch=force is for people upgrading from libreboot 5th release, where the new ROM's are "ThinkPad X60 / X60s / X60t"
# and the old ones are "ThinkPad X60 / X60s" and flashrom complains otherwise

bucts="unknown"
flashrom="unknown"
if [ -f "DEBLOB" ]; then
	bucts="./bucts/bucts"
	flashrom="./flashrom/flashrom"
elif [ $(uname -i) = "i686" ] || [ $(uname -m) = "i686" ]; then
	bucts="./bucts/i686/bucts"
	flashrom="./flashrom/i686/flashrom"
elif [ $(uname -i) = "x86_64" ] || [ $(uname -m) = "x86_64" ]; then
	bucts="./bucts/x86_64/bucts"
	flashrom="./flashrom/x86_64/flashrom"
else
	echo "This script must be run on an i686 or x86_64 host. x86_64 is recommended."
	exit 1
fi

$(echo $flashrom) -p internal -w $1

# Reset bucts back to zero
# this means we are working in src
if [ ! -f "$bucts" ]; then
	echo "WARNING: bucts not found, but if the image was flashed then it's probably safe. A dd'd image (like libreboot's images) flashed with bucts=1 is ok. If the image is not dd'd and bucts=1, then you should run ./bucts 0 now, or remove the yellow cmos/nvram battery for a minute."
	exit 1
fi

$(echo $bucts) 0
