#!/bin/bash

#  flash script: uses flashrom to flash a new libreboot ROM image onto your machine
#
#	Copyright (C) 2014 Francis Rowe <info@gluglug.org.uk>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

## Don't add this here. Errors are *expected*
# set -u -e -v
set -v

if [ $(uname -i) = "i686" ] || [ $(uname -m) = "i686" ]
	then
		echo "Running on i686. ok."
		sleep 5
elif [ $(uname -i) = "x86_64" ] || [ $(uname -m) = "x86_64" ]
	then
		echo "Running on x86_64. ok."
		sleep 5
else
	echo "This script must be run on an i686 or x86_64 host. x86_64 is recommended."
	exit 1
fi

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

# USE ROOT OR SUDO WHEN EXECUTING THIS
# uses flashrom to flash the rom

if (( $# != 1 )); then
	echo "Usage: ./lenovobios_firstflash yourrom.rom"
	echo "usage: ./lenovobios_firstflash path/to/yourrom.rom"
	echo "You need to specify exactly 1 file"
	exit 1
fi
if [ ! -f $1 ]; then
	echo "File not found!"
	exit 1
fi

# flashrom doesn't recognize the machine unless you use that switch: laptop=force_I_want_a_brick
# after flashing libreboot and booting the machine, flashing normally will just work.

if [ -f "DEBLOB" ]; then
	# Means we are in src archive or git
	./flashrom/flashrom -p internal:laptop=force_I_want_a_brick -w $1
elif [ $(uname -i) = "i686" ] || [ $(uname -m) = "i686" ]
	then
		# Means we are in bin archive and on an i686 host
		./flashrom/i686/flashrom -p internal:laptop=force_I_want_a_brick -w $1
elif [ $(uname -i) = "x86_64" ] || [ $(uname -m) = "x86_64" ]
	then
		# Means we are in bin archive and on an x86_64 host
		./flashrom/x86_64/flashrom -p internal:laptop=force_I_want_a_brick -w $1
fi
