\input texinfo
@documentencoding UTF-8

@ifnottex
@paragraphindent 0
@end ifnottex
@titlepage
@title Libreboot task list
@end titlepage

@node Top
@top Libreboot task list

@node Libreboot task list
@chapter Libreboot task list
@anchor{#libreboot-task-list}
Back to @uref{index.html,index.html}.

@node URGENT tasks for next upcoming release
@chapter URGENT tasks for next upcoming release
@anchor{#urgent-tasks-for-next-upcoming-release}
@itemize
@item
Make libreboot GNU-compatible (see libreboot.org/gnu)
@item
Fix keyboard init on x60/t60 (right now delay isn't long enough. might be fixed upstream)
@item
GM45 laptops in libreboot.git currently have uneven backlight at lower levels.
This was fixed but patch was removed due to upstream changes, with intent to
re-implement fix on top of upstream later. Do that.
@item
use the timeless branch from coreboot (rebase for different revisions). we don't need timestamps.
this is needed for reproducible builds (reproducible builds are for later release, not next release).
See @uref{https://review.coreboot.org/#/c/13412/,https://review.coreboot.org/#/c/13412/}
and @uref{https://review.coreboot.org/#/q/topic:timeless,https://review.coreboot.org/#/q/topic:timeless}
@item
(probably won't be done before release) have damo22 look into vesa framebuffer graphics on d510mo (right
now only text mode works, including in GNU/Linux)
@end itemize

@node Important tasks for the libreboot project
@chapter Important tasks for the libreboot project
@anchor{#important-tasks-for-the-libreboot-project}
This page is part of the git repository, so feel free to submit patches adding to or removing from this list. (adapting the HTML should be simple enough)

@ref{#pagetop,Back to top of page.}

@node Platform-specific bugs
@chapter Platform-specific bugs
@anchor{#platform-specific-bugs}
@itemize
@item
GM45: investigate S3/raminit on all models (CPU stepping/cpuid). Suspend is
broken in newer versions of coreboot on some libreboot laptops (e.g. GM45).
See @uref{hcl/x200.html#ram_s3_microcode,hcl/x200.html#ram_s3_microcode}
@item
KFSN4-DRE: jittery text-mode graphics. @uref{hcl/kfsn4-dre.html#issues,More info}
@item
Fix these issues on GM45/GS45 targets:
@itemize
@item
GM45: broken text-mode. Bisect of coreboot is needed, but we think that it was
broken on the very first commit that introduced native graphics initialization
and ever since. n1cky on IRC was investigating this.
@item
X60: on the latest coreboot-libre update lately (during June 2015), keyboard works intermittently. Bisect and fix.
@item
Fix remaining incompatible LCD panels in native graphics some GM45 and i945 laptops. See @uref{hcl/gm45_lcd.html,hcl/gm45_lcd.html}. - EDID related, or difference in how VGA ROM does init. Investigate.
We do not believe that this actually has anything to do with EDID. We don't
currently know what the problem is.
@end itemize

@item
@strong{Finish all work listed in @uref{future/index.html,future/index.html}}
@item
Fix these issues on i945 targets (X60/T60/macbook21)
@itemize
@item
i945: fix VRAM size (currently 8MB. should be 64MB). See @uref{future/index.html#i945_vram_size,future/index.html#i945_vram_size}.
@item
Fix remaining incompatible LCD panels in native graphics on T60. See @uref{future/index.html#lcd_i945_incompatibility,future/index.html#lcd_i945_incompatibility}. - EDID related, or difference in how VGA ROM does init. Investigate.
@end itemize

@ref{#pagetop,Back to top of page.}

@node Improvements to the utilities
@chapter Improvements to the utilities
@anchor{#improvements-to-the-utilities}
@itemize
@item
Make ich9gen/ich9deblob portable. They both rely extensively on bitfields, and they assume little-endian; for instance, mapping a little endian file directly to a struct, instead of serializing/deserializing. Re-factor both utilities and make them fully portable.
@item
Make ich9gen/ich9deblob/demefactory show GPL license info via @emph{--version} argument.
@item
Adapt linux-libre deblob scripts for use with coreboot. Libreboot is already deblobbed using its own script, but updating it is still a bit too manual. linux-libre's deblob scripts do an excellent job and (adapted) will make it much easier to maintain coreboot-libre.
@end itemize

@ref{#pagetop,Back to top of page.}

Copyright © 2014, 2015, 2016 Francis Rowe <info@@gluglug.org.uk>@* Permission is granted to copy, distribute and/or modify this document under the terms of the GNU Free Documentation License, Version 1.3 or any later version published by the Free Software Foundation; with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts. A copy of the license can be found at @uref{resources/licenses/gfdl-1.3.txt,gfdl-1.3.txt}

Updated versions of the license (when available) can be found at @uref{https://www.gnu.org/licenses/licenses.html,https://www.gnu.org/licenses/licenses.html}

UNLESS OTHERWISE SEPARATELY UNDERTAKEN BY THE LICENSOR, TO THE EXTENT POSSIBLE, THE LICENSOR OFFERS THE LICENSED MATERIAL AS-IS AND AS-AVAILABLE, AND MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND CONCERNING THE LICENSED MATERIAL, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHER. THIS INCLUDES, WITHOUT LIMITATION, WARRANTIES OF TITLE, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, ABSENCE OF LATENT OR OTHER DEFECTS, ACCURACY, OR THE PRESENCE OR ABSENCE OF ERRORS, WHETHER OR NOT KNOWN OR DISCOVERABLE. WHERE DISCLAIMERS OF WARRANTIES ARE NOT ALLOWED IN FULL OR IN PART, THIS DISCLAIMER MAY NOT APPLY TO YOU.

TO THE EXTENT POSSIBLE, IN NO EVENT WILL THE LICENSOR BE LIABLE TO YOU ON ANY LEGAL THEORY (INCLUDING, WITHOUT LIMITATION, NEGLIGENCE) OR OTHERWISE FOR ANY DIRECT, SPECIAL, INDIRECT, INCIDENTAL, CONSEQUENTIAL, PUNITIVE, EXEMPLARY, OR OTHER LOSSES, COSTS, EXPENSES, OR DAMAGES ARISING OUT OF THIS PUBLIC LICENSE OR USE OF THE LICENSED MATERIAL, EVEN IF THE LICENSOR HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH LOSSES, COSTS, EXPENSES, OR DAMAGES. WHERE A LIMITATION OF LIABILITY IS NOT ALLOWED IN FULL OR IN PART, THIS LIMITATION MAY NOT APPLY TO YOU.

The disclaimer of warranties and limitation of liability provided above shall be interpreted in a manner that, to the extent possible, most closely approximates an absolute disclaimer and waiver of all liability.

@bye
