#!/bin/bash

#  helper script: downloads coreboot and patches/deblobs it
#
#	Copyright (C) 2014, 2015 Francis Rowe <info@gluglug.org.uk>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# This script assumes that the working directory is the
# root of libreboot_src or libreboot git.

[ "x${DEBUG+set}" = 'xset' ] && set -v
set -u -e

printf "Downloading coreboot, patching coreboot and deblobbing coreboot\n"

# This grabs current base used, and applies patches
# This is also used to run the deblob scripts.

# Remove the old version that may exist
# ------------------------------------------------------------------------------

rm -Rf "coreboot/"

# Get latest coreboot:
# ------------------------------------------------------------------------------

# download it using git
git clone http://review.coreboot.org/coreboot

# there are modifications required
cd "coreboot/"

# reset to previously tested revision
git reset --hard cd5cdd3ba42371cc97b1464fd7b98de5bef05a6a

# Get patches from review.coreboot.org
# ------------------------------------------------------------------------------

# ----

# check on coreboot mailing list (see "favourites" in mail client):
# [coreboot] macbook21: broken by 10385 (Make DSDT a file in CBFS rather than embedding it into ramstage.)
# -- probably affects the X60 and T60 as well, if this is not already fixed.
# seems to be related to normal/fallback payload mechanism

# KEEP ON EYE ON:
# http://review.coreboot.org/#/c/7549

# ----

printf "southbridge/intel/common/spi: Add Flash lockdown option\n"
# git fetch http://review.coreboot.org/coreboot refs/changes/70/9370/4 && git cherry-pick FETCH_HEAD
git am "../resources/libreboot/patch/0001-southbridge-intel-common-spi-Add-Flash-lockdown-opti.patch"

printf "mainboards/lenovo/t400: Enable serial debug option for use with dock\n"
printf "NOTE: doesn't actually work at the moment. see docs/tasks.html\n"
printf "Only including so that .config doesn't have to change\n"
# git fetch http://review.coreboot.org/coreboot refs/changes/17/9317/13 && git cherry-pick FETCH_HEAD
git am "../resources/libreboot/patch/0002-mainboards-lenovo-t400-Enable-serial-debug-option-fo.patch"

printf "mainboard/lenovo/t400: Add initial hybrid graphics support\n"
# git fetch http://review.coreboot.org/coreboot refs/changes/19/9319/18 && git cherry-pick FETCH_HEAD
git am "../resources/libreboot/patch/0003-mainboard-lenovo-t400-Add-initial-hybrid-graphics-su.patch"

# not included, but keep an eye on it:
# printf "mainboard/lenovo/t400: Increase backlight frequency to reduce flicker\n"
# git fetch http://review.coreboot.org/coreboot refs/changes/31/9331/14 && git cherry-pick FETCH_HEAD

printf "NOTFORMERGE: lenovo/t400: hard-code enable integrated-only video\n"
# git fetch http://review.coreboot.org/coreboot refs/changes/50/10550/1 && git cherry-pick FETCH_HEAD
git am "../resources/libreboot/patch/0004-NOTFORMERGE-lenovo-t400-hard-code-enable-integrated-.patch"

# ----

printf "lenovo/x60: Enable VESA framebuffer mode (native graphics)\n"
# git fetch http://review.coreboot.org/coreboot refs/changes/53/10553/1 && git cherry-pick FETCH_HEAD
git am "../resources/libreboot/patch/0005-lenovo-x60-Enable-VESA-framebuffer-mode-native-graph.patch"
# NOTE: merged in master

# NOTE: Investigate what mono and mtjm wrote about bit 16 in BLC_PWM_CTL
printf "lenovo/x60: Enable legacy brightness controls (native graphics)\n"
# git fetch http://review.coreboot.org/coreboot refs/changes/48/7048/9 && git cherry-pick FETCH_HEAD
git am "../resources/libreboot/patch/0006-lenovo-x60-Enable-brightness-controls-native-graphic.patch"
# NOTE: http://review.coreboot.org/#/c/10624 is a follow-up. re-include 7048 (latest one) then include 10624
# NOTE: 7048 is now merged in coreboot master

printf "Enable T60 native graphics\n"
# git fetch http://review.coreboot.org/coreboot refs/changes/45/5345/10 && git cherry-pick FETCH_HEAD
git am "../resources/libreboot/patch/0007-lenovo-t60-Enable-native-intel-gfx-init.patch"

printf "lenovo/t60: Enable VESA framebuffer mode (native graphics)\n"
# git fetch http://review.coreboot.org/coreboot refs/changes/51/10551/1 && git cherry-pick FETCH_HEAD
git am "../resources/libreboot/patch/0008-lenovo-t60-Enable-VESA-framebuffer-mode-native-graph.patch"

printf "lenovo/t60: Enable brightness controls (native graphics)\n"
# git fetch http://review.coreboot.org/coreboot refs/changes/52/10552/1 && git cherry-pick FETCH_HEAD
git am "../resources/libreboot/patch/0009-lenovo-t60-Enable-brightness-controls-native-graphic.patch"

printf "ec/lenovo/h8: permanently enable wifi/trackpoint/touchpad/bluetooth/wwan\n"
# git fetch http://review.coreboot.org/coreboot refs/changes/58/7058/9 && git cherry-pick FETCH_HEAD
git am "../resources/libreboot/patch/0010-NOTFORMERGE-ec-lenovo-h8-wlan-trackpoint-touchpad-bl.patch"

# printf "i945: permanently set tft_brightness to 0xff. this fixes the issue with X60 and 'scrolling' backlight\n"
# git fetch http://review.coreboot.org/coreboot refs/changes/61/7561/2 && git cherry-pick FETCH_HEAD
# The patch was accidentally merged in coreboot. See 
# http://review.coreboot.org/#/c/8697/ for the revert commit. rebase 7561 and re-include it in
# libreboot, once 8697 is merged in coreboot.

printf "northbridge/gm45/raminit.c: enable GS45 high-perf (i.e. add X200S support to libreboot)\n"
# git fetch http://review.coreboot.org/coreboot refs/changes/86/7786/11 && git cherry-pick FETCH_HEAD
git am "../resources/libreboot/patch/0011-northbridge-gm45-raminit.c-enable-GS45-high-performa.patch"

printf "fix uneven backlight on X200 (when setting brightness low)\n"
# git fetch http://review.coreboot.org/coreboot refs/changes/79/7979/2 && git cherry-pick FETCH_HEAD
git am "../resources/libreboot/patch/0012-gm45-fix-uneven-backlight-native-gfx-init.patch"

printf "ThinkPad R400 support (clone of the T400)\n"
# git fetch http://review.coreboot.org/coreboot refs/changes/93/8393/5 && git cherry-pick FETCH_HEAD
git am "../resources/libreboot/patch/0013-lenovo-r400-Add-clone-of-Lenovo-T400.patch"

printf "ThinkPad T500 (depends on T400 patch)\n"
# git fetch http://review.coreboot.org/coreboot refs/changes/45/10545/1 && git cherry-pick FETCH_HEAD
git am "../resources/libreboot/patch/0014-lenovo-t500-Add-clone-of-Lenovo-T400.patch"

# Misc:

printf "ec/lenovo/h8: re-factor handling of power_management_beeps\n"
# git fetch http://review.coreboot.org/coreboot refs/changes/31/10531/8 && git cherry-pick FETCH_HEAD
git am "../resources/libreboot/patch/0015-ec-lenovo-h8-re-factor-handling-of-power_management_.patch"

# Other fixes:

printf "mainboard/asus/kfsn4-dre: Enable VGA support (without it, VGA out won't work on the KFSN4-DRE)\n"
# git fetch http://review.coreboot.org/coreboot refs/changes/73/10673/1 && git cherry-pick FETCH_HEAD
git am "../resources/libreboot/patch/0016-mainboard-asus-kfsn4-dre-Enable-VGA-support.patch"

# Run coreboot-libre deblob scripts
# ------------------------------------------------------------------------------

printf "Deleting .git* in coreboot/ (history inside .git contains the blobs that were deleted)\n"
rm -Rf ".git/"
rm -f ".gitreview"
rm -f ".gitmodules"
rm -f ".gitignore"

# Strictly overkill. libreboot doesn't even checkout this submodule
rm -Rf "3rdparty/"

cd "../"

printf "Deblobbing coreboot\n"
./resources/utilities/coreboot-libre/deblob

printf "\n\n"

# ------------------- DONE ----------------------

