#!/bin/bash

#  helper script: downloads flashrom and patches it
#
#	Copyright (C) 2014, 2015 Francis Rowe <info@gluglug.org.uk>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# This script assumes that the working directory is the
# root of libreboot_src or libreboot git.

[ "x${DEBUG+set}" = 'xset' ] && set -v
set -u -e

# Get flashrom at the last previously tested revision

# Remove the old version that may still exist:
# ------------------------------------------------------------------------------

printf "Downloading flashrom\n"

rm -Rf "flashrom/"

# Get flashrom
# ------------------------------------------------------------------------------

# download it using subversion
git clone https://github.com/stefanct/flashrom.git

cd "flashrom/"

# reset to known revision
git reset --hard 80c9382948afa5e572854d49846a36b7f9d90e03

# Apply patches
# ------------------------------------------------------------------------------

printf "Enabling whitelist for X200S, X200 Tablet, T400, T500 and R400\n"
patch "board_enable.c" < "../resources/flashrom/patch/x200s_x200t_t400_t500_r400_whitelist.diff"

printf "Enabling whitelist for Libiquity Taurinus X200\n"
patch "board_enable.c" < "../resources/flashrom/patch/0001-Add-board-enable-for-Libiquity-Taurinus-X200.patch"

# Remove redundant definitions for the flash chips that
# supported libreboot systems use. This removes the need
# for the user to run with the "-c" argument on these systems
printf "Patching flashchips.c to remove the redundant entries\n"
patch "flashchips.c" < "../resources/flashrom/patch/purged_chips.diff"

cd "../"

printf "\n\n"

# ------------------- DONE ----------------------

