#!/bin/bash

#  helper script: downloads flashrom and patches it
#
#	Copyright (C) 2014, 2015 Francis Rowe <info@gluglug.org.uk>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# This script assumes that the working directory is the
# root of libreboot_src or libreboot git.

[ "x${DEBUG+set}" = 'xset' ] && set -v
set -u -e

# Get flashrom at the last previously tested revision

# Remove the old version that may still exist:
# ---------------------------------------------------------------------

echo "DOWNLOADING FLASHROM"

rm -rf flashrom

# Get flashrom
# ---------------------------------------------------------------------

# download it using subversion
svn co -r 1858 svn://flashrom.org/flashrom/trunk flashrom

# apply patches

cd flashrom/

# Add whitelist for X200:
patch board_enable.c < ../resources/flashrom/patch/x200whitelist.diff

# Remove redundant definitions for the flash chips that
# supported libreboot machines use. This removes the need
# for the user to run with the "-c" argument on these machines
patch flashchips.c < ../resources/flashrom/patch/purged_chips.diff

cd ../

echo "FINISHED DOWNLOADING FLASHROM"

# ------------------- DONE ----------------------
