#!/bin/bash

#  helper script: Downloads GRUB and patches it.
#
#	Copyright (C) 2014, 2015 Leah Woods <info@minifree.org>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# This script assumes that the working directory is the
# root of libreboot_src or libreboot git.

[ "x${DEBUG+set}" = 'xset' ] && set -v
set -u -e

# Remove the old version that may still exist
# ------------------------------------------------------------------------------

printf "Downloading GRUB\n"

rm -Rf "grub/"

# Get latest GRUB
# ------------------------------------------------------------------------------

# download it using git
git clone git://git.savannah.gnu.org/grub.git

# modifications are required
cd "grub/"

# reset to known revision
git reset --hard 7a210304ebfd6d704b4fc08fe496a0c417441879

# Apply patches
# ------------------------------------------------------------------------------

# Replace "GNU GRUB version" in GRUB screen with "FREE AS IN FREEDOM"
git am "../resources/grub/patch/0001-grub-core-normal-main.c-Display-FREE-AS-IN-FREEDOM-n.patch"

# GRUB enhancement patches from grub.johnlane.ie
git am "../resources/grub/patch/grub.johnlane.ie/0001-Cryptomount-support-LUKS-detached-header.patch"
git am "../resources/grub/patch/grub.johnlane.ie/0002-Cryptomount-support-key-files.patch"
git am "../resources/grub/patch/grub.johnlane.ie/0003-Cryptomount-luks-allow-multiple-passphrase-attempts.patch"
git am "../resources/grub/patch/grub.johnlane.ie/0004-Cryptomount-support-plain-dm-crypt.patch"
git am "../resources/grub/patch/grub.johnlane.ie/0005-Cryptomount-support-for-hyphens-in-UUID.patch"
# hotfix from kl3 (merged from autoboot)
git am "../resources/grub/patch/grub.johnlane.ie/0006-grub-core-disk-cryptodisk.c-Point-to-const-char.patch"

cd "../"
printf "\n\n"
