#!/bin/bash

#  helper script: Downloads MemTest86+ and patches it
#
#	Copyright (C) 2014, 2015 Francis Rowe <info@gluglug.org.uk>
#	Copyright (C) 2015 Joseph Michael Thompson <jmt@josepht.me>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# This script assumes that the working directory is the
# root of libreboot_src or libreboot git.

[ "x${DEBUG+set}" = 'xset' ] && set -v
set -u -e

# Get the last version of MemTest86+ used, apply patches, build it.

# Remove the old version that may exist
# ------------------------------------------------------------------------------

printf "Downloading MemTest86+\n"

rm -Rf "memtest86+-5.01/"

# Get latest memtest86+:
# ------------------------------------------------------------------------------

# download it using wget
wget http://www.memtest.org/download/5.01/memtest86+-5.01.tar.gz

# extract it
tar -xzf "memtest86+-5.01.tar.gz"

# delete the tar file (no longer needed)
rm -f "memtest86+-5.01.tar.gz"

# there are modifications required
cd "memtest86+-5.01/"

# Apply necessary patches
# ------------------------------------------------------------------------------

# place the right config
rm -f "config.h"
cp "../resources/memtest86/patch/config.h" .

# place the right Makefile
rm -f "Makefile"
cp "../resources/memtest86/patch/Makefile" .

# (diff them with defaults to see what changed)

# we're done
cd "../"

printf "\n\n"

# ------------------- DONE ----------------------

