\input texinfo
@documentencoding UTF-8

@ifnottex
@paragraphindent 0
@end ifnottex
@titlepage
@title Libreboot documentation: Security on the ThinkPad X60
@end titlepage

@node Top
@top Libreboot documentation: Security on the ThinkPad X60

@menu
* Security on the ThinkPad X60::
* Table of Contents::
* Hardware requirements::
* Software requirements::
* Rationale::
* Disassembly::
* Extra notes::
* Further reading material software security::
* References::
@end menu

@node Security on the ThinkPad X60
@chapter Security on the ThinkPad X60
@anchor{#security-on-the-thinkpad-x60}
Hardware modifications to enhance security on the ThinkPad X60. This tutorial is @strong{incomplete} at the time of writing.

@uref{index.html,Back to previous index}

@node Table of Contents
@chapter Table of Contents
@anchor{#table-of-contents}
@itemize
@item
@ref{#hardware_requirements,Hardware Requirements}
@item
@ref{#software_requirements,Software Requirements}
@item
@ref{#procedure,The procedure}
@end itemize

@node Hardware requirements
@chapter Hardware requirements
@anchor{#hardware-requirements}
@itemize
@item
An X60
@item
screwdriver
@item
(in a later version of this tutorial: soldering iron and scalpel)
@end itemize

@node Software requirements
@chapter Software requirements
@anchor{#software-requirements}
@itemize
@item
none (at least in the scope of the article as-is)
@item
You probably want to encrypt your GNU/Linux install using LUKS
@end itemize

@node Rationale
@chapter Rationale
@anchor{#rationale}
Most people think of security on the software side: the hardware is important aswell.

This tutorial deals with reducing the number of devices that have direct memory access that could communicate with inputs/outputs that could be used to remotely command the system (or leak data). All of this is purely theoretical for the time being.

@node Disassembly
@chapter Disassembly
@anchor{#disassembly}
Firstly remove the bluetooth (if your X60 has this):@* The marked screws are underneath those stickers (marked in those 3 locations at the bottom of the LCD assembly):@* @image{../images/x60_security/0000_bluetooth0,,,,jpg}@* Now gently pry off the bottom part of the front bezel, and the bluetooth module is on the left (easily removable):@* @image{../images/x60_security/0000_bluetooth,,,,jpg}@*

If your model was WWAN, remove the simcard (check anyway):@* Uncover those 2 screws at the bottom:@* @image{../images/x60_security/0000_simcard0,,,,jpg}@* SIM card (not present in the picture) is in the marked location:@* @image{../images/x60_security/0000_simcard1,,,,jpg}@* Replacement: USB dongle.

Now get into the motherboard.

Remove those screws:@* @image{../images/x60_security/0000,,,,jpg}

Push the keyboard forward (carefully):@* @image{../images/x60_security/0001,,,,jpg}

Lift the keyboard up and disconnect it from the board:@* @image{../images/x60_security/0002,,,,jpg}

Grab the right-hand side of the chassis and force it off (gently) and pry up the rest of the chassis:@* @image{../images/x60_security/0003,,,,jpg}

You should now have this:@* @image{../images/x60_security/0004,,,,jpg}

The following is a summary of what you will remove (already done to this system):@* @image{../images/x60_security/0001_overview,,,,jpg}@* Note: the blue lines represent antenna cables and modem cables. You don't need to remove these, but you can if you want (to make it tidier after removing other parts). I removed the antenna wires, the modem jack, the modem cable and also (on another model) a device inside the part where the wwan antenna goes (wasn't sure what it was, but I knew it wasn't needed). @strong{This is optional}

Remove the microphone (can desolder it, but you can also easily pull it off with you hands). Already removed here:@* @image{../images/x60_security/0001_microphone,,,,jpg}@* @strong{Rationale:}@* Another reason to remove the microphone: If your computer gets@ref{#ref1,[1]} compromised, it can record what you say, and use it to receive data from nearby devices if they're compromised too. Also, we do not know what the built-in microcode (in the CPU) is doing; it could theoretically be programmed to accept remote commands from some speaker somewhere (remote security hole). @strong{In other words, the system could already be compromised from the factory.}

Remove the modem:@* @image{../images/x60_security/0001_modem,,,,jpg}@* (useless, obsolete device)

Remove the speaker:@* @image{../images/x60_security/0001_speaker,,,,jpg}@* Reason: combined with the microphone issue, this could be used to leak data.@* If your computer gets@ref{#ref1,[1]} compromised, it can be used to transmit data to nearby compromised devices. It's unknown if it can be turned into a microphone@ref{#ref2,[2]}.@* Replacement: headphones/speakers (line-out) or external DAC (USB).

Remove the wlan (also remove wwan if you have it):@* @image{../images/x60_security/0001_wlan_wwan,,,,jpg}@* Reason: has direct (and very fast) memory access, and could (theoretically) leak data over a side-channel.@* @strong{Wifi:} The ath5k/ath9k cards might not have firmware at all. They might safe but could have access to the computer's RAM trough DMA. If people have an intel card(most X60s come with Intel wifi by default, until you change it),then that card runs a non-free firwamre and has access to the computer's RAM trough DMA! So the risk-level is very high.@* @strong{Wwan (3g modem):} They run proprietary software! It's like AMT but over the GSM network which is probably even worse.@* Replacement: external USB wifi dongle. (or USB wwan/3g dongle; note, this has all the same privacy issues as mobile phones. wwan not recommended).
@menu
* Not covered yet::
* Also not covered yet::
@end menu

@node Not covered yet
@section Not covered yet:
@anchor{#not-covered-yet}
@itemize
@item
Disable cardbus (has fast/direct memory access)
@item
Disable firewire (has fast/direct memory access)
@item
Disable flashing the ethernet firmware
@item
Disable SPI flash writes (can be re-enabled by unsoldering two parts)
@item
Disable use of xrandr/edid on external monitor (cut 2 pins on VGA)
@item
Disable docking station (might be possible to do it in software, in coreboot upstream as a Kconfig option)
@end itemize

Go to @uref{http://media.ccc.de/browse/congress/2013/30C3_-_5529_-_en_-_saal_2_-_201312271830_-_hardening_hardware_and_choosing_a_goodbios_-_peter_stuge.html,http://media.ccc.de/browse/congress/2013/30C3_-_5529_-_en_-_saal_2_-_201312271830_-_hardening_hardware_and_choosing_a_goodbios_-_peter_stuge.html} or directly to the video: @uref{http://mirror.netcologne.de/CCC/congress/2013/webm/30c3-5529-en-Hardening_hardware_and_choosing_a_goodBIOS_webm.webm,http://mirror.netcologne.de/CCC/congress/2013/webm/30c3-5529-en-Hardening_hardware_and_choosing_a_goodBIOS_webm.webm}.

A lot of this tutorial is based on that video. Look towards the second half of the video to see how to do the above.

@node Also not covered yet
@section Also not covered yet:
@anchor{#also-not-covered-yet}
@itemize
@item
Intrusion detection: randomized seal on screws@* Just put nail polish with lot of glider on the important screws, take some good pictures. Keep the pictueres and make sure of their integrity. Compare the nail polish with the pictures before powering on the laptop.
@item
Tips about preventing/mitigating risk of cold boot attack.
@itemize
@item
soldered RAM?
@item
seal RAM door shut (possibly modified lower chassis) so that system has to be disassembled (which has to go through the nail polish)
@item
wipe all RAM at boot/power-off/power-on? (patch in coreboot upstream?)
@item
ask gnutoo about fallback patches (counts number of boots)
@end itemize

@item
General tips/advice and web links showing how to detect physical intrusions.
@item
For example: @uref{http://cs.tau.ac.il/~tromer/acoustic/,http://cs.tau.ac.il/~tromer/acoustic/} or @uref{http://cyber.bgu.ac.il/content/how-leak-sensitive-data-isolated-computer-air-gap-near-mobile-phone-airhopper,http://cyber.bgu.ac.il/content/how-leak-sensitive-data-isolated-computer-air-gap-near-mobile-phone-airhopper}.
@item
@uref{https://en.wikipedia.org/wiki/Tempest_%28codename%29,https://en.wikipedia.org/wiki/Tempest_%28codename%29}
@item
https://gitorious.org/gnutoo-for-coreboot/grub-assemble/source/a61f636797777a742f65f4c9c58032aa6a9b23c3:
@end itemize

@node Extra notes
@chapter Extra notes
@anchor{#extra-notes}
EC: Cannot be removed but can be mitigated: it contains non-free non-loadable code, but it has no access to the computer's RAM. It has access to the on-switch of the wifi, bluetooth, modem and some other power management features. The issue is that it has access to the keyboard, however if the software security howto @strong{(not yet written)} is followed correctly, it won't be able to leak data to a local attacker. It has no network access but it may still be able to leak data remotely, but that requires someone to be nearby to recover the data with the help of an SDR and some directional antennas@ref{#ref3,[3]}.

@uref{http://www.coreboot.org/Intel_82573_Ethernet_controller,Intel 82573 Ethernet controller} on the X60 seems safe, according to Denis.
@menu
* Risk level::
@end menu

@node Risk level
@section Risk level
@anchor{#risk-level}
@itemize
@item
Modem (3g/wwan): highest
@item
Intel wifi: Near highest
@item
Atheros PCI wifi: unknown, but lower than intel wifi.
@item
Microphone: only problematic if the computer gets compromised.
@item
Speakers: only problematic if the computer gets compromised.
@item
EC: can be mitigated if following the guide on software security.
@end itemize

@node Further reading material software security
@chapter Further reading material (software security)
@anchor{#further-reading-material-software-security}
@itemize
@item
@uref{../gnulinux/encrypted_trisquel.html,Installing Trisquel GNU/Linux with full disk encryption (including /boot)}
@item
@uref{../gnulinux/encrypted_parabola.html,Installing Parabola GNU/Linux with full disk encryption (including /boot)}
@item
@uref{dock.html,Notes about DMA access and the docking station}
@end itemize

@node References
@chapter References
@anchor{#references}
@menu
* [1] physical access::
* [2] microphone::
* [3] Video CCC::
@end menu

@node [1] physical access
@section [1] physical access
@anchor{#physical-access}
Explain that black hats, TAO, and so on might use a 0day to get in, and explain that in this case it mitigates what the attacker can do. Also the TAO do some evaluation before launching an attack: they take the probability of beeing caught into account, along with the kind of target. A 0day costs a lot of money, I heard that it was from 100000$ to 400000$, some other websites had prices 10 times lower but that but it was probably a typo. So if people increase their security it makes it more risky and more costly to attack people.

@node [2] microphone
@section [2] microphone
@anchor{#microphone}
It's possible to turn headphones into a microphone, you could try yourself, however they don't record loud at all. Also intel cards have the capability to change a connector's function, for instance the microphone jack can now become a headphone plug, that's called retasking. There is some support for it in GNU/Linux but it's not very well known.

@node [3] Video CCC
@section [3] Video (CCC)
@anchor{#video-ccc}
30c3-5356-en-Firmware_Fat_Camp_webm.webm from the 30th CCC. While their demo is experimental(their hardware also got damaged during the transport), the spies probably already have that since a long time. @uref{http://berlin.ftp.media.ccc.de/congress/2013/webm/30c3-5356-en-Firmware_Fat_Camp_webm.webm,http://berlin.ftp.media.ccc.de/congress/2013/webm/30c3-5356-en-Firmware_Fat_Camp_webm.webm}

Copyright © 2014, 2015 Francis Rowe <info@@gluglug.org.uk>@* Permission is granted to copy, distribute and/or modify this document under the terms of the GNU Free Documentation License, Version 1.3 or any later version published by the Free Software Foundation; with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts. A copy of the license can be found at @uref{../gfdl-1.3.txt,../gfdl-1.3.txt}

Updated versions of the license (when available) can be found at @uref{https://www.gnu.org/licenses/licenses.html,https://www.gnu.org/licenses/licenses.html}

UNLESS OTHERWISE SEPARATELY UNDERTAKEN BY THE LICENSOR, TO THE EXTENT POSSIBLE, THE LICENSOR OFFERS THE LICENSED MATERIAL AS-IS AND AS-AVAILABLE, AND MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND CONCERNING THE LICENSED MATERIAL, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHER. THIS INCLUDES, WITHOUT LIMITATION, WARRANTIES OF TITLE, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, ABSENCE OF LATENT OR OTHER DEFECTS, ACCURACY, OR THE PRESENCE OR ABSENCE OF ERRORS, WHETHER OR NOT KNOWN OR DISCOVERABLE. WHERE DISCLAIMERS OF WARRANTIES ARE NOT ALLOWED IN FULL OR IN PART, THIS DISCLAIMER MAY NOT APPLY TO YOU.

TO THE EXTENT POSSIBLE, IN NO EVENT WILL THE LICENSOR BE LIABLE TO YOU ON ANY LEGAL THEORY (INCLUDING, WITHOUT LIMITATION, NEGLIGENCE) OR OTHERWISE FOR ANY DIRECT, SPECIAL, INDIRECT, INCIDENTAL, CONSEQUENTIAL, PUNITIVE, EXEMPLARY, OR OTHER LOSSES, COSTS, EXPENSES, OR DAMAGES ARISING OUT OF THIS PUBLIC LICENSE OR USE OF THE LICENSED MATERIAL, EVEN IF THE LICENSOR HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH LOSSES, COSTS, EXPENSES, OR DAMAGES. WHERE A LIMITATION OF LIABILITY IS NOT ALLOWED IN FULL OR IN PART, THIS LIMITATION MAY NOT APPLY TO YOU.

The disclaimer of warranties and limitation of liability provided above shall be interpreted in a manner that, to the extent possible, most closely approximates an absolute disclaimer and waiver of all liability.

@bye
