\input texinfo
@documentencoding UTF-8

@ifnottex
@paragraphindent 0
@end ifnottex
@titlepage
@title Libreboot documentation: Switch heatsink on ThinkPad X60
@end titlepage

@node Top
@top Libreboot documentation: Switch heatsink on ThinkPad X60

@menu
* Changing the fan/heatsink on the ThinkPad X60::
* Table of Contents::
* Hardware requirements::
* Software requirements for CPU stress testing::
* Disassembly::
@end menu

@node Changing the fan/heatsink on the ThinkPad X60
@chapter Changing the fan/heatsink on the ThinkPad X60
@anchor{#changing-the-fanheatsink-on-the-thinkpad-x60}
This guide will teach you how to replace the fan and heatsink on your ThinkPad X60.

@uref{index.html,Back to main index}

@node Table of Contents
@chapter Table of Contents
@anchor{#table-of-contents}
@itemize
@item
@ref{#hardware_requirements,Hardware Requirements}
@item
@ref{#software_requirements,Software Requirements}
@item
@ref{#procedure,Disassembly}
@end itemize

@node Hardware requirements
@chapter Hardware requirements
@anchor{#hardware-requirements}
@itemize
@item
isopropyl alcohol (sometimes called rubbing alcohol)
@item
your new fan and/or heatsink
@item
CPU thermal compound (some say Arctic MX-4 is good, others are also 'ok')
@item
Something to spread the paste with
@end itemize

@node Software requirements for CPU stress testing
@chapter Software requirements (for CPU stress testing)
@anchor{#software-requirements-for-cpu-stress-testing}
@itemize
@item
xsensors utility
@item
stress utility
@end itemize

@node Disassembly
@chapter Disassembly
@anchor{#disassembly}
Remove those screws:@* @image{../resources/images/x60_heatsink/0000,,,,jpg}

Push the keyboard forward (carefully):@* @image{../resources/images/x60_heatsink/0001,,,,jpg}

Lift the keyboard up and disconnect it from the board:@* @image{../resources/images/x60_heatsink/0002,,,,jpg}

Grab the right-hand side of the chassis and force it off (gently) and pry up the rest of the chassis:@* @image{../resources/images/x60_heatsink/0003,,,,jpg}

You should now have this:@* @image{../resources/images/x60_heatsink/0004,,,,jpg}

Disconnect the wifi antenna cables, the modem cable and the speaker:@* @image{../resources/images/x60_heatsink/0005,,,,jpg}

Unroute the cables along their path, carefully lifting the tape that holds them in place. Then, disconnect the modem cable (other end) and power connection and unroute all the cables so that they dangle by the monitor hinge on the right-hand side:@* @image{../resources/images/x60_heatsink/0006,,,,jpg}

Disconnect the monitor from the motherboard, and unroute the grey antenna cable, carefully lifting the tape that holds it into place:@* @image{../resources/images/x60_heatsink/0008,,,,jpg}

Carefully lift the remaining tape and unroute the left antenna cable so that it is loose:@* @image{../resources/images/x60_heatsink/0009,,,,jpg}

Remove those screws:@* @image{../resources/images/x60_heatsink/0011,,,,jpg}

Remove those screws:@* @image{../resources/images/x60_heatsink/0012,,,,jpg}

Carefully remove the plate, like so:@* @image{../resources/images/x60_heatsink/0013,,,,jpg}

Remove the SATA connector:@* @image{../resources/images/x60_heatsink/0014,,,,jpg}

Now remove the motherboard (gently) and cast the lcd/chassis aside:@* @image{../resources/images/x60_heatsink/0015,,,,jpg}

Look at that black tape above the heatsink, remove it:@* @image{../resources/images/x60_heatsink/0016,,,,jpg}

Now you have removed it:@* @image{../resources/images/x60_heatsink/0017,,,,jpg}

Disconnect the fan and remove all the screws, heatsink will easily come off:@* @image{../resources/images/x60_heatsink/0018,,,,jpg}

Remove the old paste with a cloth (from the CPU and heatsink) and then clean both of them with the alcohol (to remove remaining residue of the paste). Apply a pea-sized amount of paste to the both chipsets that the heatsink covered and spread it evenly (uniformally). Finally reinstall the heatsink, reversing previous steps.

@strong{stress -c 2} command can be used to push the CPU to 100%, and @strong{xsensors} (or @strong{watch sensors} command) can be used to monitor heat. Below 90C is ok.

Copyright © 2014, 2015 Francis Rowe <info@@gluglug.org.uk>@* Permission is granted to copy, distribute and/or modify this document under the terms of the GNU Free Documentation License, Version 1.3 or any later version published by the Free Software Foundation; with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts. A copy of the license can be found at @uref{../resources/licenses/gfdl-1.3.txt,gfdl-1.3.txt}

Updated versions of the license (when available) can be found at @uref{https://www.gnu.org/licenses/licenses.html,https://www.gnu.org/licenses/licenses.html}

UNLESS OTHERWISE SEPARATELY UNDERTAKEN BY THE LICENSOR, TO THE EXTENT POSSIBLE, THE LICENSOR OFFERS THE LICENSED MATERIAL AS-IS AND AS-AVAILABLE, AND MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND CONCERNING THE LICENSED MATERIAL, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHER. THIS INCLUDES, WITHOUT LIMITATION, WARRANTIES OF TITLE, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, ABSENCE OF LATENT OR OTHER DEFECTS, ACCURACY, OR THE PRESENCE OR ABSENCE OF ERRORS, WHETHER OR NOT KNOWN OR DISCOVERABLE. WHERE DISCLAIMERS OF WARRANTIES ARE NOT ALLOWED IN FULL OR IN PART, THIS DISCLAIMER MAY NOT APPLY TO YOU.

TO THE EXTENT POSSIBLE, IN NO EVENT WILL THE LICENSOR BE LIABLE TO YOU ON ANY LEGAL THEORY (INCLUDING, WITHOUT LIMITATION, NEGLIGENCE) OR OTHERWISE FOR ANY DIRECT, SPECIAL, INDIRECT, INCIDENTAL, CONSEQUENTIAL, PUNITIVE, EXEMPLARY, OR OTHER LOSSES, COSTS, EXPENSES, OR DAMAGES ARISING OUT OF THIS PUBLIC LICENSE OR USE OF THE LICENSED MATERIAL, EVEN IF THE LICENSOR HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH LOSSES, COSTS, EXPENSES, OR DAMAGES. WHERE A LIMITATION OF LIABILITY IS NOT ALLOWED IN FULL OR IN PART, THIS LIMITATION MAY NOT APPLY TO YOU.

The disclaimer of warranties and limitation of liability provided above shall be interpreted in a manner that, to the extent possible, most closely approximates an absolute disclaimer and waiver of all liability.

@bye
